In [8]:
# VRP from google OR tools
# python files mees
pip install -upgrade -user ortools

SyntaxError: invalid syntax (<ipython-input-8-131f8509ddba>, line 3)

In [2]:
import sys
import os
import pandas as pd
sys.path.append('./ParticipantsSuite')

from InstanceCVRPTWUI import InstanceCVRPTWUI
instance = InstanceCVRPTWUI('instances/co2020_challenge_r100d10_1.txt')

In [3]:
if instance.isValid():
    instance.calculateDistances()
    import numpy
    nLoc = len(instance.Coordinates)
    d_df = pd.DataFrame([ [ instance.calcDistance[i][j] for j in range(nLoc) ] for i in range(nLoc) ])

t_df = pd.DataFrame([(i.ID, i.weight, i.amount, i.cost) for i in instance.Tools], columns=['ID','weight','amount','cost']).set_index('ID')
r_df = pd.DataFrame([(i.ID, i.node, i.fromDay, i.toDay, i.numDays, i.tool, i.toolCount) for i in instance.Requests], columns=['ID','node','fromDay','toDay','numDays','tool','toolCount']).set_index('ID')
c_df = pd.DataFrame([(i.ID, i.X, i.Y) for i in instance.Coordinates], columns=['ID','X','Y']).set_index('ID')

In [4]:
# location coordinates
c_df

       X     Y
ID
0   5445  2890
1   9432  6187
2   3500  6242
3   8109  6259
4   8105  6278
5   7406  6292
6   7324  6371
7   8424  6471
8   8023  6961
9   9177  6997
10  4570  7041
11  4316  7136
12  8709  7190
13  6029  7271
14  3527  7281
15  7522  7297
16  7793  7324
17  3817  7378
18  5651  7651
19  6682  8406
20  8429  4405
21  6120  8058
22  5469  8117
23  7722  8360
24  8047  8427
25  8864  8461
26  8271  8512
27  9131  6013
28  7903  8954
29  9656  9039
..   ...   ...
70  7849  4398
71  8107  4407
72  7735  4435
73  8189  4502
74  7709  4552
75  4116  4572
76  8533  4642
77  8426  4669
78  8460  4730
79  8122  4764
80  5443  4856
81  7274  4956
82  7185  4977
83  3794  5082
84  5068  3959
85  4486  5145
86  3152  5188
87  3184  5216
88  8964  5270
89  3768  5288
90  7866  5342
91  8077  5393
92  7564  5413
93  3818  5489
94  7398  5577
95  9146  5677
96  4909  4058
97  8366  5913
98  7070  6001
99  8199  6105

[100 rows x 2 columns]

In [5]:
def create_data_model():
    """Stores the data for the problem."""
    data = {}
    data['distance_matrix'] = [
        [
            0, 548, 776, 696, 582, 274, 502, 194, 308, 194, 536, 502, 388, 354,
            468, 776, 662
        ],
        [
            548, 0, 684, 308, 194, 502, 730, 354, 696, 742, 1084, 594, 480, 674,
            1016, 868, 1210
        ],
        [
            776, 684, 0, 992, 878, 502, 274, 810, 468, 742, 400, 1278, 1164,
            1130, 788, 1552, 754
        ],
        [
            696, 308, 992, 0, 114, 650, 878, 502, 844, 890, 1232, 514, 628, 822,
            1164, 560, 1358
        ],
        [
            582, 194, 878, 114, 0, 536, 764, 388, 730, 776, 1118, 400, 514, 708,
            1050, 674, 1244
        ],
        [
            274, 502, 502, 650, 536, 0, 228, 308, 194, 240, 582, 776, 662, 628,
            514, 1050, 708
        ],
        [
            502, 730, 274, 878, 764, 228, 0, 536, 194, 468, 354, 1004, 890, 856,
            514, 1278, 480
        ],
        [
            194, 354, 810, 502, 388, 308, 536, 0, 342, 388, 730, 468, 354, 320,
            662, 742, 856
        ],
        [
            308, 696, 468, 844, 730, 194, 194, 342, 0, 274, 388, 810, 696, 662,
            320, 1084, 514
        ],
        [
            194, 742, 742, 890, 776, 240, 468, 388, 274, 0, 342, 536, 422, 388,
            274, 810, 468
        ],
        [
            536, 1084, 400, 1232, 1118, 582, 354, 730, 388, 342, 0, 878, 764,
            730, 388, 1152, 354
        ],
        [
            502, 594, 1278, 514, 400, 776, 1004, 468, 810, 536, 878, 0, 114,
            308, 650, 274, 844
        ],
        [
            388, 480, 1164, 628, 514, 662, 890, 354, 696, 422, 764, 114, 0, 194,
            536, 388, 730
        ],
        [
            354, 674, 1130, 822, 708, 628, 856, 320, 662, 388, 730, 308, 194, 0,
            342, 422, 536
        ],
        [
            468, 1016, 788, 1164, 1050, 514, 514, 662, 320, 274, 388, 650, 536,
            342, 0, 764, 194
        ],
        [
            776, 868, 1552, 560, 674, 1050, 1278, 742, 1084, 810, 1152, 274,
            388, 422, 764, 0, 798
        ],
        [
            662, 1210, 754, 1358, 1244, 708, 480, 856, 514, 468, 354, 844, 730,
            536, 194, 798, 0
        ],
    ]
    data['num_vehicles'] = 4
    data['depot'] = 0
    return data

In [6]:
# inlcude distance metric. manhatten is used here

def distance_callback(from_index, to_index):
    """Returns the distance between the two nodes."""
    # Convert from routing variable Index to distance matrix NodeIndex.
    from_node = manager.IndexToNode(from_index)
    to_node = manager.IndexToNode(to_index)
    return data['distance_matrix'][from_node][to_node]

transit_callback_index = routing.RegisterTransitCallback(distance_callback)
routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)

NameError: name 'routing' is not defined